### ISSUE TITLE
Heading sizes are not semantic

### ISSUE THREAD

**Issue by josephshambrook** [fakesamgregory/brAND#25]
The headings don't make semantic sense at the moment. By design, they should go from largest to smallest, but headings 2 and 3 are switched round, and it would make sense to switch them round for brAND.

With font size changes, the hierarchy of headings makes more sense.
![image](https://user-images.githubusercontent.com/751062/35438316-ef7f27c2-028d-11e8-85f8-3eeba46a5fb9.png)

As a side effect, the headings for Modules are different, but I also feel this makes more sense too. The major heading for this section is larger than the headings for each feature list item.
![image](https://user-images.githubusercontent.com/751062/35438514-bca6f716-028e-11e8-98d4-64c1ca7d6610.png)

**Comment by fakesamgregory** [comment]
@josephshambrook I think this is such a valid point. I do however think we are labelling these incorrectly. This is a module so the 'guide', 'build' and 'teach' are simply links styled in this way and are not headers. `h3` appear in this type of module but appear different at 18px.
