### ISSUE TITLE
There does not seem to be a Charcoal theme

### ISSUE THREAD

**Issue by rereed92** [fakesamgregory/brAND#46]
## Expected behavior
I have the option to choose a blue-theme, pink-theme to change the colour of the navigation links, but I am not able to change them to charcoal

## Actual behavior
I should be able to have a class for a charcoal theme

**Comment by fakesamgregory** [comment]
@rereed92 There is no 'charcoal theme' as this is is assumed default. Let me run it by Angel. 

Thanks

**Comment by rereed92** [comment]
@fakesamgregory I am not able to make a link charcoal though, should I be able to do this?

**Comment by fakesamgregory** [comment]
@rereed92 I don't think links should be charcoal

**Comment by rereed92** [comment]
@fakesamgregory as discussed with Angel, this is no longer an issue as links should always be coloured.  This issue can be closed down.

**Comment by fakesamgregory** [comment]
@rereed92 Thank you Becky appreciate the time to raise
